# app/mock_data/products_seed.py

import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from app.utils.database import db
from app.models.product import Product
from app import create_app

app = create_app()

mock_products = [

    {"name": "Wireless Headphones", "description": "Bluetooth noise-canceling headphones", "price": 2999.99, "category": "electronics"},
    {"name": "Sci-Fi Novel", "description": "Bestselling science fiction book", "price": 499.99, "category": "books"},
    {"name": "Cotton T-Shirt", "description": "Comfortable round-neck t-shirt", "price": 299.99, "category": "textiles"},
    {"name": "Bluetooth Speaker", "description": "Portable wireless speaker", "price": 1499.99, "category": "electronics"},
    {"name": "Running Shoes", "description": "Lightweight and durable running shoes", "price": 2999.50, "category": "shoes"},
    {"name": "Yoga Mat", "description": "Non-slip and eco-friendly yoga mat", "price": 899.00, "category": "fitness"},
    {"name": "Smart Watch", "description": "Tracks fitness and health data", "price": 4599.00, "category": "electronics"},
    {"name": "Hoodie", "description": "Warm cotton hoodie for winter", "price": 1200.00, "category": "clothing"},
    {"name": "Fiction Novel", "description": "Bestselling fiction book", "price": 499.00, "category": "books"},
    {"name": "Casual T-shirt", "description": "Comfy everyday wear", "price": 350.00, "category": "clothing"},
    {"name": "Wireless Earbuds", "description": "High quality sound", "price": 2499.00, "category": "electronics"},
    {"name": "Sandals", "description": "Comfortable open footwear", "price": 799.00, "category": "shoes"},
    {"name": "Resistance Bands", "description": "Full body workout tool", "price": 450.00, "category": "fitness"},
    {"name": "Hair Dryer", "description": "Compact and fast drying", "price": 1100.00, "category": "home_appliances"},
    {"name": "Romance Novel", "description": "Heartwarming love story", "price": 399.00, "category": "books"},
    {"name": "Sunglasses", "description": "UV protection and stylish", "price": 999.00, "category": "fashion"},
    {"name": "Fitness Tracker", "description": "Steps and calories counter", "price": 1899.00, "category": "electronics"},
    {"name": "Formal Shirt", "description": "Perfect for office wear", "price": 999.00, "category": "clothing"},
    {"name": "Leather Boots", "description": "Durable and elegant", "price": 3599.00, "category": "shoes"},
    {"name": "Electric Kettle", "description": "1.5L auto-off feature", "price": 1299.00, "category": "home_appliances"},
    {"name": "Mystery Novel", "description": "Page-turning suspense", "price": 450.00, "category": "books"},
    {"name": "Backpack", "description": "Waterproof and stylish", "price": 1450.00, "category": "fashion"},
    {"name": "Bluetooth Keyboard", "description": "Rechargeable and quiet keys", "price": 2200.00, "category": "electronics"},
    {"name": "Track Pants", "description": "Ideal for workout or casual wear", "price": 800.00, "category": "clothing"},
    {"name": "Slip-on Loafers", "description": "Comfort and convenience", "price": 1399.00, "category": "shoes"},
    {"name": "Dumbbells Set", "description": "Adjustable weights", "price": 2899.00, "category": "fitness"},
    {"name": "Air Purifier", "description": "Removes dust and allergens", "price": 6599.00, "category": "home_appliances"},
    {"name": "Fantasy Novel", "description": "Epic adventures and battles", "price": 550.00, "category": "books"},
    {"name": "Makeup Kit", "description": "All essentials in one box", "price": 2499.00, "category": "fashion"},
    {"name": "Gaming Mouse", "description": "Ergonomic and fast response", "price": 1599.00, "category": "electronics"},
    {"name": "Winter Jacket", "description": "Insulated for cold weather", "price": 2999.00, "category": "clothing"},
    {"name": "Formal Shoes", "description": "Ideal for meetings", "price": 2599.00, "category": "shoes"},
    {"name": "Treadmill", "description": "Foldable and sturdy", "price": 22999.00, "category": "fitness"},
    {"name": "Iron Press", "description": "Quick heating plate", "price": 999.00, "category": "home_appliances"},
    {"name": "Self-help Book", "description": "Improve your daily habits", "price": 300.00, "category": "books"},
    {"name": "Necklace Set", "description": "Elegant occasion wear", "price": 1799.00, "category": "fashion"},
    {"name": "Laptop Stand", "description": "Adjustable and foldable", "price": 700.00, "category": "electronics"},
    {"name": "Casual Shorts", "description": "Breathable cotton fabric", "price": 499.00, "category": "clothing"},
    {"name": "Sports Shoes", "description": "Shock absorption sole", "price": 2199.00, "category": "shoes"},
    {"name": "Pull-up Bar", "description": "Fits standard door frames", "price": 1599.00, "category": "fitness"},
    {"name": "Toaster", "description": "2-slice pop-up toaster", "price": 850.00, "category": "home_appliances"},
    {"name": "Thriller Novel", "description": "Gripping and fast-paced", "price": 400.00, "category": "books"},
    {"name": "Handbag", "description": "Trendy and spacious", "price": 1999.00, "category": "fashion"},
    {"name": "Portable Charger", "description": "10000mAh fast charging", "price": 1199.00, "category": "electronics"},
    {"name": "Kurta Set", "description": "Ethnic wear for occasions", "price": 1600.00, "category": "clothing"},
    {"name": "Canvas Sneakers", "description": "Trendy and comfy", "price": 1250.00, "category": "shoes"},
    {"name": "Ab Roller", "description": "Build core strength", "price": 699.00, "category": "fitness"},
    {"name": "Hair Straightener", "description": "Silk smooth finish", "price": 1399.00, "category": "home_appliances"},
    {"name": "Biography Book", "description": "Inspiring life journey", "price": 499.00, "category": "books"},
    {"name": "Watch for Women", "description": "Classy dial with leather strap", "price": 1599.00, "category": "fashion"},
    {"name": "USB Hub", "description": "4-port with fast transfer", "price": 450.00, "category": "electronics"},
    {"name": "Leggings", "description": "Stretchable and comfy", "price": 399.00, "category": "clothing"},
    {"name": "Oxford Shoes", "description": "Perfect for formal events", "price": 2499.00, "category": "shoes"},
    {"name": "Skipping Rope", "description": "Foam handle jump rope", "price": 299.00, "category": "fitness"},
    {"name": "Electric Cooker", "description": "Auto cooking functions", "price": 1999.00, "category": "home_appliances"},
    {"name": "Children's Storybook", "description": "Fun and educational", "price": 299.00, "category": "books"},
    {"name": "Lipstick Set", "description": "5 shades pack", "price": 899.00, "category": "fashion"},
    {"name": "Denim Jacket", "description": "Classic blue denim", "price": 1899.00, "category": "clothing"},
    {"name": "Beanie Hat", "description": "Winter wear woolen hat", "price": 299.00, "category": "fashion"},
    {"name": "Wireless Mouse", "description": "Ergonomic and rechargeable", "price": 799.00, "category": "electronics"},
    {"name": "Graphic T-shirt", "description": "Trendy printed tee", "price": 499.00, "category": "clothing"},
    {"name": "Flip Flops", "description": "Comfortable rubber sole", "price": 349.00, "category": "shoes"},
    {"name": "Gym Gloves", "description": "Anti-slip weightlifting gloves", "price": 399.00, "category": "fitness"},
    {"name": "Coffee Maker", "description": "Brew hot coffee instantly", "price": 2999.00, "category": "home_appliances"},
    {"name": "Travel Guide Book", "description": "Explore top travel destinations", "price": 450.00, "category": "books"},
    {"name": "Wallet", "description": "Genuine leather slim wallet", "price": 799.00, "category": "fashion"},
    {"name": "Power Bank", "description": "20000mAh high-speed", "price": 1799.00, "category": "electronics"},
    {"name": "Chinos", "description": "Smart casual cotton pants", "price": 1299.00, "category": "clothing"},
    {"name": "Sneakers for Kids", "description": "Comfortable and colorful", "price": 999.00, "category": "shoes"},
    {"name": "Foam Roller", "description": "For muscle relaxation", "price": 799.00, "category": "fitness"},
    {"name": "Blender", "description": "Multipurpose food blender", "price": 2299.00, "category": "home_appliances"},
    {"name": "Cookbook", "description": "Healthy meals for home", "price": 399.00, "category": "books"},
    {"name": "Earrings", "description": "Gold-plated fashion earrings", "price": 499.00, "category": "fashion"},
    {"name": "LED Monitor", "description": "24-inch Full HD", "price": 7499.00, "category": "electronics"},
    {"name": "Polo Shirt", "description": "Comfortable semi-formal", "price": 799.00, "category": "clothing"},
    {"name": "Leather Sandals", "description": "Handmade ethnic design", "price": 899.00, "category": "shoes"},
    {"name": "Protein Shaker", "description": "Leak-proof BPA-free", "price": 299.00, "category": "fitness"},
    {"name": "Microwave Oven", "description": "20L auto-cook menu", "price": 5799.00, "category": "home_appliances"},
    {"name": "Poetry Book", "description": "Collection of modern poems", "price": 349.00, "category": "books"},
    {"name": "Fashion Belt", "description": "Synthetic leather belt", "price": 499.00, "category": "fashion"},
    {"name": "Tablet", "description": "10.1-inch display, 4G", "price": 8999.00, "category": "electronics"},
    {"name": "Joggers", "description": "For sports and daily wear", "price": 999.00, "category": "clothing"},
    {"name": "Formal Heels", "description": "Block heel pumps", "price": 1599.00, "category": "shoes"},
    {"name": "Push-up Bars", "description": "Sturdy fitness equipment", "price": 499.00, "category": "fitness"},
    {"name": "Air Fryer", "description": "Oil-less cooking", "price": 6999.00, "category": "home_appliances"},
    {"name": "Children's Puzzle Book", "description": "Mind games & puzzles", "price": 199.00, "category": "books"},
    {"name": "Anklet", "description": "Silver-plated, boho design", "price": 299.00, "category": "fashion"},
    {"name": "Portable Fan", "description": "USB rechargeable", "price": 599.00, "category": "electronics"},
    {"name": "Raincoat", "description": "Waterproof and packable", "price": 699.00, "category": "clothing"},
    {"name": "Lace-up Boots", "description": "Stylish and rugged", "price": 2199.00, "category": "shoes"},
    {"name": "Pull-up Resistance Bands", "description": "Heavy-duty", "price": 649.00, "category": "fitness"},
    {"name": "Hand Blender", "description": "Compact and quick blending", "price": 1299.00, "category": "home_appliances"},
    {"name": "Graphic Novel", "description": "Full-color illustrated", "price": 699.00, "category": "books"},
    {"name": "Hairband Set", "description": "5 colorful bands", "price": 199.00, "category": "fashion"},
    {"name": "VR Headset", "description": "Immersive gaming experience", "price": 3999.00, "category": "electronics"},
    {"name": "Tank Top", "description": "Cool and comfy summer wear", "price": 399.00, "category": "clothing"},
    {"name": "Clogs", "description": "Slip-on for daily use", "price": 599.00, "category": "shoes"},
    {"name": "Kettlebell", "description": "8kg for strength training", "price": 899.00, "category": "fitness"},
    {"name": "Room Heater", "description": "Electric fan heater", "price": 2099.00, "category": "home_appliances"},
    {"name": "Notebook Set", "description": "3 ruled notebooks", "price": 199.00, "category": "books"},
    {"name": "Nail Polish Kit", "description": "6 bright colors", "price": 299.00, "category": "fashion"},
    {"name": "Gaming Keyboard", "description": "RGB mechanical keys", "price": 2499.00, "category": "electronics"},
    {"name": "Pajama Set", "description": "Cotton nightwear set", "price": 899.00, "category": "clothing"},
    {"name": "Slip-on Shoes", "description": "Minimal and trendy", "price": 1199.00, "category": "shoes"},
    {"name": "Smart Scale", "description": "Tracks weight & BMI", "price": 1499.00, "category": "fitness"},
    {"name": "Electric Grill", "description": "Non-stick surface", "price": 3499.00, "category": "home_appliances"},
    {"name": "Bluetooth Speaker", "description": "Portable and waterproof", "price": 1999.00, "category": "electronics"},
    {"name": "Trendy Hoodie", "description": "Unisex warm hoodie", "price": 1199.00, "category": "clothing"},
    {"name": "Running Shoes", "description": "Lightweight for joggers", "price": 2499.00, "category": "shoes"},
    {"name": "Fitness Tracker", "description": "Steps, heart rate, sleep", "price": 3499.00, "category": "fitness"},
    {"name": "Toaster", "description": "2-slice browning control", "price": 1599.00, "category": "home_appliances"},
    {"name": "Mystery Novel", "description": "Thrilling crime story", "price": 499.00, "category": "books"},
    {"name": "Leather Jacket", "description": "Genuine leather biker style", "price": 4599.00, "category": "clothing"},
    {"name": "Ankle Boots", "description": "Stylish winter footwear", "price": 1799.00, "category": "shoes"},
    {"name": "Yoga Mat", "description": "Non-slip and cushioned", "price": 799.00, "category": "fitness"},
    {"name": "Hand Mixer", "description": "Multiple speed options", "price": 1999.00, "category": "home_appliances"},
    {"name": "Classic Novel", "description": "A timeless literary piece", "price": 299.00, "category": "books"},
    {"name": "Choker Necklace", "description": "Black velvet choker", "price": 249.00, "category": "fashion"},
    {"name": "Smartphone", "description": "4G LTE dual SIM", "price": 8999.00, "category": "electronics"},
    {"name": "Cargo Pants", "description": "Utility multi-pocket design", "price": 1299.00, "category": "clothing"},
    {"name": "Canvas Sneakers", "description": "Everyday comfort wear", "price": 999.00, "category": "shoes"},
    {"name": "Dumbbell Set", "description": "Pair of 5kg weights", "price": 1599.00, "category": "fitness"},
    {"name": "Induction Cooktop", "description": "Fast electric cooking", "price": 3199.00, "category": "home_appliances"},
    {"name": "Biography", "description": "Story of an inspiring leader", "price": 399.00, "category": "books"},
    {"name": "Bracelet", "description": "Charm bracelet for girls", "price": 349.00, "category": "fashion"},
    {"name": "Digital Camera", "description": "DSLR with 18-55mm lens", "price": 29999.00, "category": "electronics"},
    {"name": "Formal Shirt", "description": "Slim fit, wrinkle-free", "price": 899.00, "category": "clothing"},
    {"name": "Slip-on Loafers", "description": "Elegant office wear", "price": 1499.00, "category": "shoes"},
    {"name": "Resistance Bands", "description": "Set of 5 elastic bands", "price": 599.00, "category": "fitness"},
    {"name": "Rice Cooker", "description": "1.8L auto-warm feature", "price": 2199.00, "category": "home_appliances"},
    {"name": "Comic Book", "description": "Superhero adventures", "price": 249.00, "category": "books"},
    {"name": "Watch", "description": "Analog silver wristwatch", "price": 1099.00, "category": "fashion"},
    {"name": "Laptop", "description": "i5, 8GB RAM, SSD", "price": 42999.00, "category": "electronics"},
    {"name": "Tracksuit", "description": "Full sleeve and joggers set", "price": 1799.00, "category": "clothing"},
    {"name": "Sports Shoes", "description": "For running & gym", "price": 1999.00, "category": "shoes"},
    {"name": "Kettlebell Set", "description": "6kg and 10kg pair", "price": 2299.00, "category": "fitness"},
    {"name": "Juicer", "description": "Centrifugal fruit juicer", "price": 2999.00, "category": "home_appliances"},
    {"name": "Children’s Storybook", "description": "Bedtime moral stories", "price": 199.00, "category": "books"},
    {"name": "Hair Clips Set", "description": "Pack of 12 trendy clips", "price": 149.00, "category": "fashion"},
    {"name": "Noise-Canceling Earbuds", "description": "Bluetooth 5.0 enabled", "price": 1799.00, "category": "electronics"},
    {"name": "Thermal Leggings", "description": "Winter base layer", "price": 699.00, "category": "clothing"},
    {"name": "Boots", "description": "Snow resistant waterproof", "price": 2499.00, "category": "shoes"},
    {"name": "Pull-up Bar", "description": "Adjustable door frame bar", "price": 1199.00, "category": "fitness"},
    {"name": "Air Purifier", "description": "HEPA filter for rooms", "price": 7499.00, "category": "home_appliances"},
    {"name": "Cookbook for Teens", "description": "Quick meals and snacks", "price": 349.00, "category": "books"},
    {"name": "Sunglasses", "description": "UV protection polarized", "price": 699.00, "category": "fashion"},
    {"name": "Smartwatch", "description": "Fitness tracking enabled", "price": 2999.00, "category": "electronics"},
    {"name": "Printed Skirt", "description": "Floral midi skirt", "price": 899.00, "category": "clothing"},
    {"name": "Running Trainers", "description": "Men’s breathable sports shoes", "price": 1899.00, "category": "shoes"},
    {"name": "Treadmill", "description": "Foldable with incline", "price": 19999.00, "category": "fitness"},
    {"name": "Electric Chopper", "description": "Chops onions, veggies", "price": 1699.00, "category": "home_appliances"},
    {"name": "Romantic Novel", "description": "Heartwarming modern love story", "price": 399.00, "category": "books"},
    {"name": "Fashion Handbag", "description": "PU leather with compartments", "price": 1499.00, "category": "fashion"},
    {"name": "Soundbar", "description": "Powerful bass, HDMI ARC", "price": 4999.00, "category": "electronics"},
    {"name": "Graphic Sweatshirt", "description": "Casual oversized fit", "price": 1099.00, "category": "clothing"}
]







with app.app_context():
    db.create_all()  # Ensure tables exist

    # Optional: Clear old mock data
    Product.query.delete()

    for p in mock_products:
        product = Product(
            name=p["name"],
            description=p["description"],
            price=p["price"],
            category=p["category"]
        )
        db.session.add(product)

    db.session.commit()
    print("✅ Mock products inserted successfully.")
